# Generated by Django 5.1 on 2024-08-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-time_create'], 'verbose_name': 'Оборудование'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='место установки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['-time_create'], name='equipment_e_time_cr_8a5ef7_idx'),
        ),
    ]
