# Generated by Django 5.1 on 2024-08-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options_equipment_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
