# Generated by Django 5.1 on 2024-08-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-time_create'], 'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
    ]
