# Generated by Django 5.1 on 2024-08-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_category_options_alter_equipment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.category'),
        ),
    ]
