# Generated by Django 5.1 on 2024-08-20 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_equipment_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equip', to='equipment.category', verbose_name='категория'),
        ),
    ]
