# Generated by Django 5.1 on 2024-08-20 09:09

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_alter_equipment_cat'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
