# Generated by Django 5.1 on 2024-08-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_equipment_photo_alter_equipment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='название'),
        ),
    ]
